[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
ffi = false

# Gas reporting
gas_reports = ["*"]

[dependencies]
forge-std = "1.12.0"

[fuzz]
runs = 256

[profile.ci]
verbosity = 3

[profile.ci.fuzz]
runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
